export const SET_POKEMON_LIST          = 'SET_POKEMON_LIST'
export const REQUEST_LOAD_POKEMON_LIST = 'REQUEST_LOAD_POKEMON_LIST'
export const SUCCESS_LOAD_POKEMON_LIST = 'SUCCESS_LOAD_POKEMON_LIST'
export const FAILURE_LOAD_POKEMON_LIST = 'FAILURE_LOAD_POKEMON_LIST'
