export const SET_TYPE_FILTER     = 'SET_TYPE_FILTER'
export const SET_TYPE_LIST       = 'SET_TYPE_LIST'
export const START_LOADING_TYPES = 'START_LOADING_TYPES'
export const STOP_LOADING_TYPES  = 'STOP_LOADING_TYPES'
