export const CHANGE_TYPE_FILTER   = 'CHANGE_TYPE_FILTER'
export const SET_TYPE_FILTER_LIST = 'SET_TYPE_FILTER_LIST'
export const START_LOADING_TYPES  = 'START_LOADING_TYPES'
export const STOP_LOADING_TYPES   = 'STOP_LOADING_TYPES'
