export const SET_POKEMON_LIST           = 'SET_POKEMON_LIST'
export const START_LOADING_POKEMON_LIST = 'START_LOADING_POKEMON_LIST'
export const STOP_LOADING_POKEMON_LIST  = 'STOP_LOADING_POKEMON_LIST'
